/**
 * The canonical formatter, plus an opt-in aligned house style.
 */
import { parse, quoteName, quoteValue } from "./parser.js";
import { SPEC_VERSION, type Line } from "./types.js";

export interface FormatOptions {
  /**
   * Column-align attribute containers so the tree silhouette stays clean
   * in policy-heavy drafts. An alternative formatting profile, not the
   * canonical form: fmt --check without --align still expects
   * single-space output.
   */
  align?: boolean;
}

interface RawItem {
  raw: string;
}
interface EntryItem {
  head: string;
  attrs: string[];
  comment: string;
  opensBlock: boolean;
  indent: string;
}
type Item = RawItem | EntryItem;

const ALIGN_CAP = 48;

/** One attribute in canonical source form. */
function renderAttr(key: string, value: string | null, values: string[]): string {
  if (value === null) return key;
  if (values.length > 1) return `${key}: [${values.map(quoteValue).join(", ")}]`;
  if (values.length === 0) return `${key}: []`;
  return `${key}: ${quoteValue(values[0])}`;
}

/** The entry head: indent, path or quoted name, `/`, `?`. */
function renderHead(line: Line, indent: string): string {
  const base = line.path ? line.path.join("/") : quoteName(line.name);
  const optional = line.annotations.some((a) => !a.fromProfile && a.key === "optional");
  return indent + base + (line.isFolder ? "/" : "") + (optional ? "?" : "");
}

/**
 * Canonical formatter. Normalizes indentation to 2 spaces per level,
 * single-spaces container items, quotes names and values only when
 * necessary, prefers the `?` sigil over the `optional` word, and
 * collapses runs of blank lines. Conservative by design: any line
 * carrying an error is left verbatim. Idempotent, aligned or not.
 */
export function format(text: string, options: FormatOptions = {}): string {
  const res = parse(text);
  // The no-rewrite rule: a draft declaring a newer format than this library
  // implements is returned unchanged. Best-effort rewriting risks corruption.
  if (res.version > SPEC_VERSION) return text;
  const items: Item[] = [];
  let blankRun = 0;

  for (const line of res.lines) {
    if (line.kind === "blank") {
      if (++blankRun === 1 && items.length > 0) items.push({ raw: "" });
      continue;
    }
    blankRun = 0;

    if (line.kind === "comment") {
      items.push({ raw: line.raw.trimEnd() });
      continue;
    }
    if (line.errors.some((e) => e.severity === "error")) {
      items.push({ raw: line.raw.trimEnd() }); // leave broken lines exactly as written
      continue;
    }
    if (line.kind === "pragma") {
      const comment = line.spans.comment
        ? " " + line.raw.slice(line.spans.comment[0] - line.from).trimEnd()
        : "";
      items.push({ raw: `drafteine ${line.version}` + comment });
      continue;
    }
    if (line.kind === "annotation" || line.kind === "block-end") {
      continue; // clean container lines are regenerated by their owning entry
    }

    const indent = "  ".repeat(line.depth);
    const attrs = line.annotations
      .filter((a) => !a.fromProfile && a.key !== "optional")
      .map((a) => renderAttr(a.key, a.value, a.values));
    items.push({
      indent,
      head:
        line.kind === "preset"
          ? `preset ${line.presetName ?? line.name}`
          : renderHead(line, indent),
      attrs,
      comment: line.spans.comment
        ? " " + line.raw.slice(line.spans.comment[0] - line.from).trimEnd()
        : "",
      opensBlock: line.opensBlock === true,
    });
  }

  // Alignment column: longest head among inline attributed entries, capped.
  let alignTo = 0;
  if (options.align) {
    for (const item of items) {
      if ("raw" in item) continue;
      if (item.attrs.length === 0 || item.opensBlock) continue;
      if (item.head.length <= ALIGN_CAP) alignTo = Math.max(alignTo, item.head.length);
    }
  }

  const out: string[] = [];
  for (const item of items) {
    if ("raw" in item) {
      out.push(item.raw);
      continue;
    }
    if (item.attrs.length === 0) {
      out.push(item.head + item.comment);
      continue;
    }
    const inline = `${item.head} { ${item.attrs.join(", ")} }${item.comment}`;
    // The comment never forces expansion: only the entry and its
    // attributes count against the line budget.
    if (item.opensBlock || inline.length - item.comment.length > 80) {
      out.push(item.head + " {" + item.comment);
      for (const a of item.attrs) out.push(item.indent + "  " + a);
      out.push(item.indent + "}");
      continue;
    }
    if (options.align && item.head.length <= ALIGN_CAP) {
      const pad = " ".repeat(alignTo - item.head.length + 1);
      out.push(`${item.head}${pad}{ ${item.attrs.join(", ")} }${item.comment}`);
      continue;
    }
    out.push(inline);
  }

  while (out.length > 0 && out[out.length - 1] === "") out.pop();
  return out.length === 0 ? "" : out.join("\n") + "\n";
}
