/**
 * The canonical formatter, plus an opt-in aligned house style.
 */
import { parse, quoteName, quoteValue } from "./parser.js";
import { SPEC_VERSION } from "./types.js";

export interface FormatOptions {
  /**
   * Column-align annotations so the tree silhouette stays clean in
   * policy-heavy drafts. An alternative formatting profile, not the
   * canonical form: fmt --check without --align still expects
   * single-space output.
   */
  align?: boolean;
}

interface RawItem {
  raw: string;
}
interface EntryItem {
  head: string;
  anns: string[];
  comment: string;
  opensBlock: boolean;
  indent: string;
}
type Item = RawItem | EntryItem;

const ALIGN_CAP = 48;

/**
 * Canonical formatter. Normalizes indentation to 2 spaces per level,
 * single-spaces annotations, quotes names/values only when necessary, and
 * collapses runs of blank lines. Conservative by design: any line carrying
 * an error is left verbatim. Idempotent, aligned or not.
 */
export function format(text: string, options: FormatOptions = {}): string {
  const res = parse(text);
  // The no-rewrite rule: a draft declaring a newer format than this library
  // implements is returned unchanged. Best-effort rewriting risks corruption.
  if (res.version > SPEC_VERSION) return text;
  const items: Item[] = [];
  let blankRun = 0;

  for (const line of res.lines) {
    if (line.kind === "blank") {
      if (++blankRun === 1 && items.length > 0) items.push({ raw: "" });
      continue;
    }
    blankRun = 0;

    if (line.kind === "comment") {
      items.push({ raw: line.raw.trimEnd() });
      continue;
    }
    if (line.errors.some((e) => e.severity === "error")) {
      items.push({ raw: line.raw.trimEnd() }); // leave broken lines exactly as written
      continue;
    }
    if (line.kind === "pragma") {
      const comment = line.spans.comment
        ? " " + line.raw.slice(line.spans.comment[0] - line.from).trimEnd()
        : "";
      items.push({ raw: `drafteine ${line.version}` + comment });
      continue;
    }
    if (line.kind === "annotation" || line.kind === "block-end") {
      continue; // clean block lines are regenerated by their owning entry
    }

    const indent = "  ".repeat(line.depth);
    items.push({
      indent,
      head: indent + quoteName(line.name) + (line.isFolder ? "/" : ""),
      anns: line.annotations
        .filter((a) => !a.fromProfile)
        .map((a) =>
          a.value === null ? `@${a.key}` : `@${a.key}(${a.values.map(quoteValue).join(", ")})`
        ),
      comment: line.spans.comment
        ? " " + line.raw.slice(line.spans.comment[0] - line.from).trimEnd()
        : "",
      opensBlock: line.opensBlock === true,
    });
  }

  // Alignment column: longest head among inline annotated entries, capped.
  let alignTo = 0;
  if (options.align) {
    for (const item of items) {
      if ("raw" in item) continue;
      if (item.anns.length === 0 || item.opensBlock) continue;
      if (item.head.length <= ALIGN_CAP) alignTo = Math.max(alignTo, item.head.length);
    }
  }

  const out: string[] = [];
  for (const item of items) {
    if ("raw" in item) {
      out.push(item.raw);
      continue;
    }
    const inline =
      item.head + (item.anns.length ? " " + item.anns.join(" ") : "") + item.comment;
    if (item.anns.length > 0 && (item.opensBlock || inline.length > 80)) {
      out.push(item.head + " {" + item.comment);
      for (const a of item.anns) out.push(item.indent + "  " + a);
      out.push(item.indent + "}");
      continue;
    }
    if (options.align && item.anns.length > 0 && item.head.length <= ALIGN_CAP) {
      const pad = " ".repeat(alignTo - item.head.length + 1);
      out.push(item.head + pad + item.anns.join(" ") + item.comment);
      continue;
    }
    out.push(inline);
  }

  while (out.length > 0 && out[out.length - 1] === "") out.pop();
  return out.length === 0 ? "" : out.join("\n") + "\n";
}
