/**
 * Materialization: a parse tree becomes an ordered operation list.
 */
import type { PlanOp, TreeNode } from "./types.js";

/**
 * Turn a parse tree into a materialization plan: an ordered list of
 * filesystem operations. Nodes with errors on their line are skipped, so
 * the plan only ever contains what parsed clean.
 */
export function plan(root: TreeNode): PlanOp[] {
  const ops: PlanOp[] = [];
  walk(root, "");
  return ops;

  function walk(node: TreeNode, prefix: string): void {
    for (const child of node.children) {
      if (child.line!.errors.some((e) => e.severity === "error")) continue;
      if (child.annotations.some((a) => a.key === "forbidden")) continue;
      const path = prefix + child.name + (child.isFolder ? "/" : "");
      const template = child.annotations.find((a) => a.key === "template");
      ops.push({
        type: child.isFolder ? "mkdir" : "touch",
        path,
        template: template?.value ?? null,
      });
      if (child.isFolder) walk(child, prefix + child.name + "/");
    }
  }
}

/** Render a plan as a copy-pasteable shell script. */
export function toScript(ops: PlanOp[]): string {
  const header = [
    "#!/usr/bin/env bash",
    "# Generated by Drafteine. Review before running.",
    "set -euo pipefail",
    "",
  ];
  const body = ops.map((op) => {
    const q = shellQuote(op.path.replace(/\/$/, ""));
    const note = op.template ? `  # template: ${op.template}` : "";
    return op.type === "mkdir" ? `mkdir -p ${q}${note}` : `touch ${q}${note}`;
  });
  return header.concat(body).join("\n") + "\n";
}

function shellQuote(s: string): string {
  return /^[\w./-]+$/.test(s) ? s : `'${s.replace(/'/g, `'\\''`)}'`;
}
