/**
 * CODEOWNERS generation from owner attributes. Parents emit before
 * children because CODEOWNERS applies the last matching rule, so deeper
 * entries override their ancestors. Bare tokens get an @ prefix.
 */
import type { TreeNode } from "@drafteine/core";

export function buildCodeowners(root: TreeNode, displayName: string): string {
  const lines: string[] = [
    `# Generated by drafteine from ${displayName}. Edit the draft, not this file.`,
  ];
  const walk = (node: TreeNode, prefix: string): void => {
    for (const child of node.children) {
      if (child.line!.errors.some((e) => e.severity === "error")) continue;
      const p = prefix + child.name;
      const owner = child.annotations.find((a) => a.key === "owner");
      if (owner && owner.value) {
        const owners = owner.value
          .split(/\s+/)
          .filter(Boolean)
          .map((t) => (t.includes("@") ? t : "@" + t))
          .join(" ");
        const pattern = "/" + p.replace(/ /g, "\\ ") + (child.isFolder ? "/" : "");
        lines.push(`${pattern} ${owners}`);
      }
      if (child.isFolder) walk(child, p + "/");
    }
  };
  walk(root, "");
  return lines.join("\n") + "\n";
}
