/**
 * Onboarding and ownership queries: init scaffolds a project's contract
 * and agent rules, owner resolves which @owner covers a path.
 */
import fs from "node:fs";
import path from "node:path";
import { parse, quoteName, type TreeNode } from "@drafteine/core";

const INIT_IGNORE = new Set([".git", "node_modules", "dist", "coverage"]);

function snapshotTree(dir: string, depth: number, out: string[]): void {
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  const visible = entries.filter((e) => !INIT_IGNORE.has(e.name));
  visible.sort((a, b) =>
    a.isDirectory() === b.isDirectory()
      ? a.name < b.name ? -1 : 1
      : a.isDirectory() ? -1 : 1
  );
  for (const e of visible) {
    const isDir = e.isDirectory();
    out.push("  ".repeat(depth) + quoteName(e.name) + (isDir ? "/" : ""));
    if (isDir) snapshotTree(path.join(dir, e.name), depth + 1, out);
  }
}

export const AGENT_RULES = `## Drafteine structure contract

This project's file structure is governed by structure.dft. Rules:

1. Before creating any file, declare it in structure.dft first and show
   that draft diff for authorization. Folders end with /, two-space
   indentation nests, annotations trail the name (@strict,
   @max-lines(n), @forbidden, @count(n), @optional).
2. Run npx drafteine check --all before starting work and again after
   every change set.
3. Never run drafteine accept autonomously. Accepting drift into the
   contract is a decision for a human reviewer: propose the change and
   wait. Never regenerate the whole draft, targeted edits only.
4. Policy violations (@max-lines, @forbidden, @count) are decisions:
   fix reality or change the annotation deliberately, never both
   casually.
`;

export function runInit(rootDir: string, agents: boolean): string[] {
  const notes: string[] = [];
  const draftPath = path.join(rootDir, "structure.dft");
  const configPath = path.join(rootDir, "drafteine.config.json");

  if (fs.existsSync(draftPath)) {
    notes.push("structure.dft already exists, left untouched");
  } else {
    const lines = ["# Structure contract. Generated by drafteine init from the current tree.", ""];
    snapshotTree(rootDir, 0, lines);
    fs.writeFileSync(draftPath, lines.join("\n") + "\n");
    notes.push("wrote structure.dft from a snapshot of the current tree");
  }

  if (fs.existsSync(configPath)) {
    notes.push("drafteine.config.json already exists, left untouched");
  } else {
    fs.writeFileSync(configPath, JSON.stringify({ contracts: ["structure.dft"] }, null, 2) + "\n");
    notes.push("wrote drafteine.config.json");
  }

  if (agents) {
    const agentsPath = path.join(rootDir, "AGENTS.md");
    const existing = fs.existsSync(agentsPath) ? fs.readFileSync(agentsPath, "utf8") : "";
    if (existing.includes("Drafteine structure contract")) {
      notes.push("AGENTS.md already carries the drafteine rules");
    } else {
      fs.writeFileSync(agentsPath, existing + (existing ? "\n" : "") + AGENT_RULES);
      notes.push("appended agent rules to AGENTS.md");
    }
  }
  return notes;
}

/** Deepest @owner covering a draft-relative path, or null. */
export function resolveOwner(source: string, relPath: string): string | null {
  const result = parse(source);
  const segments = relPath.split("/").filter(Boolean);
  let node: TreeNode | undefined = result.root;
  let owner: string | null = null;
  for (const segment of segments) {
    node = node.children.find((c) => c.name === segment);
    if (!node) break;
    const a = node.annotations.find((x) => x.key === "owner");
    if (a && a.value) owner = a.value;
  }
  return owner;
}
